### ISSUE TITLE
It seems to be '+=' instead of  '+'

### ISSUE THREAD

**Issue by Triple-ROCK** [mdeib/berkeley-deep-RL-pytorch-solutions#1]
https://github.com/mdeib/berkeley-deep-RL-pytorch-solutions/blob/edbbc6da17cafe25ac630189c17d365bb8983af3/hw2/cs285/agents/pg_agent.py#L129

**Comment by mdeib** [comment]
Nice Catch, it should be += instead of =. I have made the change in the code and will update the results soon.
