### ISSUE TITLE
It seems to be another loop instead of "mod"

### ISSUE THREAD

**Issue by Triple-ROCK** [mdeib/berkeley-deep-RL-pytorch-solutions#2]
https://github.com/mdeib/berkeley-deep-RL-pytorch-solutions/blob/7f2a5e180ef0c047f7cb39a054e97b8fd63004b7/hw3/cs285/critics/bootstrapped_continuous_critic.py#L55

**Comment by mdeib** [comment]
This one is correct as is. The code inside that if statement updates the target, so the target only gets updated every num_grad_steps_per_target_update. This means every target is updated num_grad_steps_per_target_update times before a new target is calculated, which is precisely what we want. This section of code can also be formulated as a nested for loop with some rearrangement of code, but there is no error as currently written.

**Comment by Triple-ROCK** [comment]
> This one is correct as is. The code inside that if statement updates the target, so the target only gets updated every num_grad_steps_per_target_update. This means every target is updated num_grad_steps_per_target_update times before a new target is calculated, which is precisely what we want. This section of code can also be formulated as a nested for loop with some rearrangement of code, but there is no error as currently written.

sorry, I didn't notice that you had used multiplication in the above, as I instead used two loops
