### ISSUE TITLE
Excuse me, Some trouble with training time.

### ISSUE THREAD

**Issue by Triple-ROCK** [mdeib/berkeley-deep-RL-pytorch-solutions#3]
hello, I met some problems in hw2 training HalfCheetah with batch size 30000, It takes me just a few seconds to collect data in hw3 within same batch size, but In hw2, it will take several minutes, which is really confusing, would you please tell me what may be wrong with it ? Thank you !

**Comment by mdeib** [comment]
Rerunning the code on my end both seem to take about 25 seconds or so, so I was unable to reproduce the problem. I was also unable to find any relevant errors in the code, so unfortunately I do not have an answer for you. Just make sure you don't have any other intensive programs running in the background and double check any changes you may have made. You should also double-check that you are using the same hyper-parameters (where relevant). If everything else seems to be working correctly it should not be a problem.
